# Numpy (Part-2)

In [1]:
import numpy as np

In [6]:
empty = np.empty((2,4))
print(empty)
print("-" * 50)
print(empty[1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
--------------------------------------------------
[0. 0. 0. 0.]


In [7]:
x = np.arange(23)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [8]:
# array of even numbers
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [9]:
# array of odd numbers
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [10]:
# specific difference between numbers
diff = np.arange(0, 23, 0.5)
diff 

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5])

In [11]:
lin = np.linspace(0, 10, num=15)
lin

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [12]:
lin.dtype

dtype('float64')

In [13]:
# define the dtype of array
x = np.arange(0 ,22.6, 1.5, dtype=np.int8)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int8)

# What is the difference between int32, 64 ya float 32, 64, 16....?

In programming, **int32, int64, float32, float64, and float16** are different data types used to represent numbers.

**int32** and **int64** are integer data types that can store whole numbers. The difference between them is the range of values they can represent. int32 can store values between -2,147,483,648 and 2,147,483,647, while int64 can store values between -9,223,372,036,854,775,808 and 9,223,372,036,854,775,807.

**float32** and **float64** are floating-point data types that can store decimal numbers. The difference between them is the precision and range of values they can represent. float32 can store values between -3.4028235e+38 and 3.4028235e+38 with a precision of 6-9 decimal digits, while float64 can store values between -1.7976931348623157e+308 and 1.7976931348623157e+308 with a precision of 15-17 decimal digits.

**float16** is a half-precision floating-point data type that can store values between -65504 and 65504 with a precision of 3-4 decimal digits. It is used in machine learning applications where memory usage and computation speed are more important than precision.

The choice of data type depends on the specific use case. If you need to store whole numbers and do not require a large range of values, int32 is a good choice. If you need to store decimal numbers and require high precision, float64 is a good choice. If you need to store decimal numbers and memory usage or computation speed is a concern, float32 or float16 may be a better choice.

In **MATLAB**, the data types are similar but have different names. int32 and int64 are represented as int32 and int64, respectively. float32 and float64 are represented as single and double, respectively. float16 is not directly supported in MATLAB, but can be represented using the half data type from the Fixed-Point Designer toolbox.

In summary, the choice of data type depends on the specific use case and the trade-off between precision, range, memory usage, and computation speed.

In [14]:
# sorting an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [15]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [17]:
# concatenate these arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenate 2D Arrays


In [18]:
x = np.array([[1,2], [3,4]]) # 2x2 array
y = np.array([[5,6]]) # 1x2 array

In [19]:
len(x)

2

In [20]:
len(y)

1

In [21]:
# concatenate 2D arrays
z = np.concatenate((x, y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
w = np.array([[5,1], [7,1]]) # 2x2 array
x = np.array([[1, 2], [3, 4]]) # 2x2 array

In [25]:
z1 = np.concatenate((w,x), axis=1)
z2 = np.concatenate((w,x), axis=0)
print(z1)
print("-" * 50)
print(z2)

[[5 1 1 2]
 [7 1 3 4]]
--------------------------------------------------
[[5 1]
 [7 1]
 [1 2]
 [3 4]]


# 3D array

In [26]:
# create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example.ndim

3

In [27]:
len(array_example)

3

In [28]:
array_example.size

24

In [29]:
array_example.dtype

dtype('int32')

In [30]:
array_example.shape

(3, 2, 4)

In [32]:
# creata 3D array of size (3,1,4)
a1 = np.array([[[0, 1, 2, 3]],
                [[4, 5, 6, 7]],
                [[0, 1, 2, 3]]])
a1.shape

(3, 1, 4)

In [33]:
# reshape the a 
a2 = a1.reshape(6,2)
a2.shape

(6, 2)

In [34]:
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [35]:
a2.reshape(3,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [36]:
# create a 1D array
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [37]:
# convert that into 2D array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [40]:
c = a[: , np.newaxis]
print(c.shape)
print(c)

(8, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# indexing and slicing

In [41]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [43]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
b[b <= 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
b[b % 2 == 0] # filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [46]:
b[b % 2 == 1] # filter odd numbers

array([ 1,  3,  5,  7,  9, 11])

In [47]:
# use two conditions
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
# use three conditions
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [49]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])