# Numpy

Numerical Python 

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

- Powerful N-dimensional arrays tools.
- Numerical computing tools.

Documentation: https://numpy.org/doc/stable/

In [2]:
# # installing library
# pip install numpy

## What is an array?

An array is a data structure in programming that stores a collection of elements, typically of the same data type, in a contiguous block of memory. It is a fundamental concept in many programming languages, including Python, and is used extensively in scientific computing, data analysis, and machine learning.

In Python, the NumPy library provides support for arrays and enables efficient numerical operations on them. NumPy arrays are more efficient than Python lists for numerical operations because they are implemented in C and allow for vectorized operations.

In [3]:
# importing library
import numpy as np

In [4]:
a = np.arange(6)
print(a)
a.shape

[0 1 2 3 4 5]


(6,)

In [5]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [6]:
a3 = a2[np.newaxis, :]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Why do we have 1D, 2D or 3D arrays and where we need them in Data Science?

1D, 2D, or 3D arrays are used to store data in a structured manner. 1D arrays are used for single-dimensional data, while 2D and 3D arrays are used for multi-dimensional data.

In Data Science, **1D arrays** can be used to store a list of values, such as a list of ages or a list of temperatures. **2D arrays** can be used to store data in a grid-like structure, such as a table of data with rows and columns. **3D arrays** can be used to store data in a cube-like structure, with multiple layers of data.

- 1D array:

In [7]:
import numpy as np

# Create a 1D array
arr1d = np.array([1, 2, 3, 4, 5])

# Access an element in the array
print(arr1d[0]) # Output: 1

# Add an element to the array
arr1d = np.append(arr1d, 6)
print(arr1d) # Output: [1 2 3 4 5 6]

1
[1 2 3 4 5 6]


- 2D array:

In [8]:
# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access an element in the array
print(arr2d[0, 0]) # Output: 1

# Add a row to the array
arr2d = np.vstack((arr2d, np.array([10, 11, 12])))
print(arr2d) # Output: [[ 1  2  3]
# [ 4  5  6]
# [ 7  8  9]
# [10 11 12]]

1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


- 3D array:

In [10]:
import numpy as np

# Create two 3D arrays
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr2 = np.array([[[13, 14, 15], [16, 17, 18]], [[19, 20, 21], [22, 23, 24]]])

# Concatenate the arrays along the first axis (axis=0)
arr3 = np.concatenate((arr1, arr2), axis=0)

# Print the resulting array
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]]]


---

## Creating Arrays with Numpy

In [11]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([(1,2,3,4,5,6,7), (4,5,6,7,8,9,10)])

In [12]:
type(a) # type of array

numpy.ndarray

In [13]:
a.dtype # data type of array element

dtype('int32')

In [14]:
type(b)

numpy.ndarray

In [16]:
b.dtype

dtype('int32')

In [17]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [18]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

## initialize arrays

In [19]:
zeros = np.zeros((2,5)) # (rows,columns)
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
zeros.dtype

dtype('float64')

In [21]:
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [24]:
full = np.full((2,5), 9)
full

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [25]:
full.dtype

dtype('int32')

In [26]:
identity = np.eye(5) # creating an identity matrix
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
identity.dtype

dtype('float64')

# array attributes

In [28]:
a.shape # shape of array

(7,)

In [29]:
len(b) # give us the length of array

2

In [30]:
b.size # gives us the numbers of elements in array

14

In [31]:
b.ndim # give us the dimension of array

2

## basic operations

In [32]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [34]:
g = a - b # subtraction
g

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [35]:
# addition
h = a + b
h 

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [36]:
# another method
h1 = np.add(a, b)
h1

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [37]:
# multiplication
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [38]:
# division
j = a / b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

In [39]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
# square of each element
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])