In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [25]:
# Assume User Input
# Pclass/gender/age/SibSp/Parch/Fare/embarked
test_input = np.array([1, 'female', 25.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)

In [26]:
test_input

array([[1, 'female', 25.0, 0, 0, 10.5, 'S']], dtype=object)

In [27]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\n\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [28]:
test_input_sex

array([[1., 0.]])

In [29]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [30]:
test_input_embarked

array([[0., 0., 1.]])

In [31]:
test_input_age = test_input[:,2].reshape(1,1)

In [32]:
test_input_age

array([[25.0]], dtype=object)

In [33]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]], test_input_age, test_input_sex, test_input_embarked), axis=1)

In [34]:
test_input_transformed.shape

(1, 10)

In [35]:
clf.predict(test_input_transformed)

array([0], dtype=int64)