In [1]:
sherry = open("dataset3.txt").read()
sherry

'milk bread bread bread : grocery\nbread milk milk bread : grocery\nmilk milk milk bread bread bread bread : grocery\ncat cat cat dog dog bark : pets\ndog dog cat bark mew mew : pets\ncat dog cat dog mew cat :'

In [2]:
ok = sherry.split("\n")
ok

['milk bread bread bread : grocery',
 'bread milk milk bread : grocery',
 'milk milk milk bread bread bread bread : grocery',
 'cat cat cat dog dog bark : pets',
 'dog dog cat bark mew mew : pets',
 'cat dog cat dog mew cat :']

In [8]:
x=[]
y=[]
for item in ok:
    text,label = item.split(":")
    x.append(text.strip())
    y.append(label.strip())
    

In [9]:
x

['milk bread bread bread',
 'bread milk milk bread',
 'milk milk milk bread bread bread bread',
 'cat cat cat dog dog bark',
 'dog dog cat bark mew mew',
 'cat dog cat dog mew cat']

In [10]:
y

['grocery', 'grocery', 'grocery', 'pets', 'pets', '']

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
data_x = cv.fit_transform(x)
data_x


<6x6 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [14]:
data_x.toarray()

array([[0, 3, 0, 0, 0, 1],
       [0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3],
       [1, 0, 3, 2, 0, 0],
       [1, 0, 1, 2, 2, 0],
       [0, 0, 3, 2, 1, 0]], dtype=int64)

In [15]:
corpus = ['milk bread bread bread',
        'bread milk milk bread',
        'milk milk milk bread bread bread bread',
        'cat cat cat dog dog bark',
        'dog dog cat bark mew mew',
        'cat dog cat dog mew']
corpus

['milk bread bread bread',
 'bread milk milk bread',
 'milk milk milk bread bread bread bread',
 'cat cat cat dog dog bark',
 'dog dog cat bark mew mew',
 'cat dog cat dog mew']

In [16]:
cv = CountVectorizer()
data_K = cv.fit_transform(corpus)
data_K

<6x6 sparse matrix of type '<class 'numpy.int64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [17]:
data_K.toarray()

array([[0, 3, 0, 0, 0, 1],
       [0, 2, 0, 0, 0, 2],
       [0, 4, 0, 0, 0, 3],
       [1, 0, 3, 2, 0, 0],
       [1, 0, 1, 2, 2, 0],
       [0, 0, 2, 2, 1, 0]], dtype=int64)

In [18]:
from sklearn.cluster import KMeans

In [20]:
km = KMeans(n_clusters=2)
km.fit(data_K[:5])

KMeans(n_clusters=2)

In [30]:
labels = km.labels_
labels

array([0, 0, 0, 1, 1])

In [31]:
km.predict(data_K[5])

array([1])

In [32]:
for i in range(len(labels)):
    label = labels[i]
    text = corpus[i]
    print(f"(label {label}): {text}")

(label 0): milk bread bread bread
(label 0): bread milk milk bread
(label 0): milk milk milk bread bread bread bread
(label 1): cat cat cat dog dog bark
(label 1): dog dog cat bark mew mew


In [33]:
from nltk import pos_tag

In [35]:
corpus1 = 'I like this table in my room'
corpus1 = corpus1.split(" ")
corpus1

['I', 'like', 'this', 'table', 'in', 'my', 'room']

In [36]:
tags = pos_tag(corpus1)
tags

[('I', 'PRP'),
 ('like', 'VBP'),
 ('this', 'DT'),
 ('table', 'NN'),
 ('in', 'IN'),
 ('my', 'PRP$'),
 ('room', 'NN')]