## Introducing Numpy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices.

- **Data Types and Shapes**
  - Scalar
  - Vectors
  - Matrices
  - Tensors
  - Changing Shapes
  - Commonly used initializations

- **Element Wise Operation**
  - The Python way
  - The NumPy way
  - Element-wise Matrix Operations

- **NumPy Matrix Multiplication**
  - Element-wise Multiplication
  - Matrix Product
  - NumPys dot function
  - Transpose

- **Sorting, Subsetting, Slicing, Splitting and Indexing**

In [2]:
# import library
import numpy as np

## Data Types and Shapes

The most common way to work with numbers in NumPy is through ndarray objects. Thery are similar to Python lists, but can have any number of dimensions. Also, ndarray supports fast math operations, which is just what we want.

Since it can store any number of dimensions, we can use ndarray's to represent any of the data types: 

- Scalars
- Vectors
- Matrices
- Tensors

## Scalars

Scalars in NumPy are a bit more involved than in Python. Instead of Python's basic types like int, float, etc., NumPy lets we specify signed and unsigned types, as well as different sizes. So instead of Python's int, we have access to types like uint8, int8, uint16, int16, and so on.

These types are important because every object we make (vectors, matrices, tensors) eventually stores scalars. And when we create a NumPy array, we can specify the type - **but every item in the array must have the same type**. In this regard, NumPy arrays are more like C arrays than Python lists.

If we want to create a NumPy array that holds a scalar, we can do so by passing the value to NumPy's array function, like so:

In [3]:
s = np.array(5)
print(s)

5


In [4]:
# shape of our array
print(s.shape)

()


- Here, this empty pair of **parenthesis ()** indicates that it has **zero dimensions**.

In [12]:
x = s + 3
print(x)

8


In [13]:
print(type(x))

<class 'numpy.int32'>


In [14]:
print(x.shape)
# x = 8
# print(x.shape)

()


## Vectors

To create a vector, we'd pass a Python list to the array function, like this:

In [15]:
v = np.array([1,2,3,4,5])
print(v)

[1 2 3 4 5]


In [16]:
# check shape
print(v.shape)

(5,)


- Now that there is a number, we can see that the shape is a tuple with the sizes of each of the ndarray 's dimensions. 
- For **scalars** it was just an empty tuple, but **vectors** have one dimension, so the tuple includes a number and a comma.
- Python doesn't understand (3) as a tuple with one item, so it requires the comma.

In [17]:
# accessing item in vector
x = v[1]
print(x)

2


## Matrices


We can create matrices using NumPy's array function, similar to that of vectors. However, instead of just passing in a list, we need to supply a list of lists, where each list represents a row. So to create a 3x3 matrix containing the numbers one through nine, we could do this:

In [19]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("m = \n",m, )
print("m.shape:", m.shape)

m = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
m.shape: (3, 3)


- m is thus a (3,3) tuple. This indicates that it has two dimensions each of size 3. We can access elements of matrices just like vectors but additional index values.

In [20]:
# accessing element
print(m[1][2])

6


## Tensors

Tensors are just like vectors and matrices, **but they can have more dimensions**.

For example, to create a 3x3x2x1 tensor, we could do the following:

In [27]:
t = np.array([[
    [[1],[2]], [[3],[4]], [[4],[5]],\
        [[6],[7]], [[7],[8]], [[8],[9]],\
            [[9],[10]], [[10],[11]], [[11],[12]],\
]])

In [28]:
print(t.shape)

(1, 9, 2, 1)


In [30]:
t[0,4]

array([[7],
       [8]])

- `Size` function which returns the total number of elements in an array.

In [31]:
print(t.size)

18


## Changing Shapes

- Sometimes we need to change the shape of our data without actually changing the content.
- For example, we may have a vector, which is one-dimensional, but need a matrix, which is two-dimensional.

In [32]:
v = np.array([1,2,3,4])

In [33]:
print(v.shape)

(4,)


In [34]:
# 1x4 matrix
x = v.reshape(1,4)

In [35]:
print(x.shape)

(1, 4)


In [36]:
print(x)

[[1 2 3 4]]


In [37]:
# 4x1 matrix
x = v.reshape(4,1)
print(x.shape)
print(x) 

(4, 1)
[[1]
 [2]
 [3]
 [4]]


In [38]:
# We have matrix A
A = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
x = A.reshape(2,6)
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## Commonly Used Initilizations

In [40]:
a = np.zeros((3,4))
print(a.shape)
print(a)

(3, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
a = np.ones((3,2,2))
print(a)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [43]:
a = np.random.rand(3,5)
print(a)

[[0.72238531 0.65795314 0.73193924 0.361499   0.94142669]
 [0.25772851 0.79432977 0.43811966 0.84143946 0.8875978 ]
 [0.12856463 0.84898421 0.06072346 0.06379779 0.81462284]]


In [44]:
a = np.random.randn(50,100)
print(a.mean())
print(np.std(a)**2)

0.0038480117826439836
1.0070831565239695


In [45]:
a

array([[-1.11731749, -0.83231033,  0.64648328, ...,  0.75305574,
        -0.73771529, -1.64768293],
       [ 0.12858262,  0.38874918,  0.22129821, ..., -1.49577999,
         0.39131029, -1.22963294],
       [-0.83386706, -1.78931047,  0.12014107, ..., -1.18454287,
         0.1600025 ,  1.93109068],
       ...,
       [-0.62104817, -0.76313758, -0.01597626, ..., -0.45525703,
         0.62902737,  0.83889227],
       [-1.61272413, -0.8857467 , -1.07926646, ..., -1.5934398 ,
        -0.97685306,  0.05360186],
       [ 1.67620519,  1.00685153, -0.18138342, ..., -1.15514131,
        -0.19518415, -1.80291903]])

## Element Wise Operations

- The Python Way

In [46]:
values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
print(values)

[6, 7, 8, 9, 10]


- Numpy Way

In [47]:
values = [1,2,3,4,5]
values = np.array(values) + 5
print(values)

[ 6  7  8  9 10]


In [48]:
x = np.multiply(values, 5)
print(x)

[30 35 40 45 50]
